name: user_repository
description: Dart package which manages the user.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5

  # Firebase
  firebase_auth: ^4.8.0
  cloud_firestore: ^4.9.0
  firebase_storage: ^11.1.0
  firebase_core: ^2.9.0
  flutter_facebook_auth: ^6.0.4
  google_sign_in: ^6.2.1
  flutter_line_sdk: ^2.3.6
  shared_preferences: ^2.2.2
  cloud_functions: ^4.6.1
  firebase_database: ^10.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
