name: instax
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  image_picker: ^1.0.4
  image_cropper: ^5.0.0
  intl: ^0.19.0
  google_sign_in: ^6.2.1
  flutter_line_sdk: ^2.3.6

  # Firebase
  firebase_core: ^2.9.0
  firebase_auth: ^4.17.7
  flutter_facebook_auth: ^6.0.3

  # BLoC
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  badges: ^3.1.2

  # Custom Repository
  user_repository:
    path: packages/user_repository
  post_repository:
    path: packages/post_repository
  job_repository:
    path: packages/job_repository
  job_post_repository:
    path: packages/job_post_repository
  chat_repository:
    path: packages/chat_repository
  shared_preferences: ^2.2.2
  firebase_storage: ^11.6.0
  http: ^1.2.0
  cloud_functions: ^4.6.1
  share_plus: ^7.2.2
  social_share: ^2.3.1
  url_launcher: ^6.2.4
  firebase_dynamic_links: ^5.4.13
  go_router: ^13.2.0
  uni_links: ^0.5.1
  firebase_database: ^10.4.6
  photo_view: ^0.14.0
  path_provider: ^2.1.2
  flutter_local_notifications: ^16.3.3
  awesome_notifications: ^0.9.2
  firebase_messaging: ^14.7.18
  firebase_analytics: ^10.8.8
  overlay_support: ^2.1.0
  in_app_notification: ^1.1.2
  lifecycle: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: NotoSansThai
      fonts:
        - asset: assets/fonts/NotoSansThai-Light.ttf
        - asset: assets/fonts/NotoSansThai-Regular.ttf
        - asset: assets/fonts/NotoSansThai-Medium.ttf
        - asset: assets/fonts/NotoSansThai-SemiBold.ttf
