name: instax
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  image_picker: ^1.0.4
  image_cropper: ^5.0.0
  intl: ^0.18.1
  google_sign_in: ^6.2.1

  # Firebase
  firebase_core: ^2.9.0
  firebase_auth: ^4.16.0
  flutter_facebook_auth: ^6.0.3

  # BLoC
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  badges: ^3.1.2

  # Custom Repository
  user_repository:
    path: packages/user_repository
  post_repository:
    path: packages/post_repository
  job_repository:
    path: packages/job_repository
  job_post_repository:
    path: packages/job_post_repository
  shared_preferences: ^2.2.2
  firebase_storage: ^11.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: NotoSansThai
      fonts:
        - asset: assets/fonts/NotoSansThai-Light.ttf
        - asset: assets/fonts/NotoSansThai-Regular.ttf
        - asset: assets/fonts/NotoSansThai-Medium.ttf
        - asset: assets/fonts/NotoSansThai-SemiBold.ttf
