// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdP8Hb1rkl575xF3hmJhP96h4MvlNPJ34',
    appId: '1:483434719398:android:2f0c677e97158268d6ac67',
    messagingSenderId: '483434719398',
    projectId: 'plawarn-6704c',
    databaseURL:
        'https://plawarn-6704c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'plawarn-6704c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMi0eaWPFbw71Exy5Ju41QVpzlkZlS7Tg',
    appId: '1:483434719398:ios:df2c12e86f007628d6ac67',
    messagingSenderId: '483434719398',
    projectId: 'plawarn-6704c',
    databaseURL:
        'https://plawarn-6704c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'plawarn-6704c.appspot.com',
    androidClientId:
        '483434719398-06hl0h7o7188kh8uupe6b61lb51k1c25.apps.googleusercontent.com',
    iosClientId:
        '483434719398-pad1b4ipc2i64ke21s9sb4i1ur1ck03r.apps.googleusercontent.com',
    iosBundleId: 'com.example.instax',
  );
}
