name: chat_repository
description: Dart package which manages the chat.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.0.0

  # Firebase
  cloud_firestore: ^4.9.0
  firebase_database: ^10.4.6
  firebase_storage: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
